@include('Frontend.Layout.head')
@include('Frontend.Layout.sidebar')
@include('Frontend.Layout.header')
@include('Frontend.Layout.footer')

@yield('head')
@yield('sidebar')
@yield('header')
@yield('content')
@yield('footer')
